[project]
name = "finance.danielmoessner.de"
version = "0.0.0"
description = ""
authors = [
    {name = "danielmoessner", email = "github@danielmoessner.de"},
]
dependencies = [
    "beautifulsoup4>=4.12.2",
    "django>=4.2.3",
    "django-debug-toolbar>=4.1.0",
    "Jinja2>=3.1.2",
    "numpy>=1.25.1",
    "pandas>=1.2.4",
    "pytz>=2023.3",
    "requests>=2.31.0",
    "scipy>=1.9.3",
    "pydantic>=2.0.3",
    "selenium>=4.10.0",
    "webdriver-manager>=3.9.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
