[project]
name = ""
version = ""
description = ""
authors = [
    {name = "danielmoessner", email = "github@danielmoessner.de"},
]
dependencies = [
    "beautifulsoup4>=4.9.3",
    "Django>=3.2.4",
    "django-debug-toolbar>=3.2.1",
    "Jinja2>=2.11.3",
    "numpy>=1.20.2",
    "pandas>=1.2.4",
    "pytz>=2021.1",
    "requests>=2.25.1",
    "scipy>=1.9.3",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
