[tool.black]
line-length = 88

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
check_untyped_defs = true
exclude = ["migrations", "__pypackages__", "venv"]

[tool.django-stubs]
django_settings_module = "config.settings.local"
ignore_missing_settings = true

[tool.isort]
known_local_folder = ["dms", "seedwork"]
profile = "black"

[tool.ruff]
# Enable pycodestyle (`E`) and Pyflakes (`F`) codes by default.
# select = ["F"]
exclude = [
    "config/settings"
]

[project]
name = "finance.danielmoessner.de"
version = "0.0.0"
description = ""
authors = [
    {name = "danielmoessner", email = "github@danielmoessner.de"},
]
dependencies = [
    "beautifulsoup4>=4.12.2",
    "django>=4.2.3",
    "django-debug-toolbar>=4.2.0",
    "Jinja2>=3.1.2",
    "numpy>=1.25.1",
    "pandas>=2.0.3",
    "pytz>=2023.3",
    "requests>=2.31.0",
    "pydantic>=2.1.1",
    "selenium>=4.10.0",
    "webdriver-manager>=4.0.0",
    "isort>=5.12.0",
    "black>=23.7.0",
    "ruff>=0.0.280",
    "mypy>=1.4.1",
    "django-types>=0.17.0",
    "django-stubs[compatible-mypy]>=4.2.3",
    "types-requests>=2.31.0.2",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
