name: Deploy

on:
  workflow_dispatch

jobs:
  build:
    name: Run deploy script
    runs-on: ubuntu-latest
    steps:
    - name: Login to the remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: /home/finance.danielmoessner.de/deploy.sh
